### ISSUE TITLE
Add-on installs and activates without errors, panel is not added to sequencer (Blender 3.4.1)

### ISSUE THREAD

**Issue by josephclaytonhansen** [tin2tin/auto_range#1]
Add-on doesn't seem to work on Blender 3.4.1, no errors are logged in the system console but nothing shows up and no operators are added to the F3 menu. 
![2023-03-03 18_54_11-Window](https://user-images.githubusercontent.com/45859835/222863584-db98ec39-49b5-49a1-826d-44f7ff57e8b6.png)

**Comment by tin2tin** [comment]
That's really weird. It works when copy/paste the code into the text editor and run it there, but not when installing it. Thanks for the rapport.

**Comment by tin2tin** [comment]
Stupid error, the version number was too low. Should be fixed now.
